import Head from "next/head";
import React from "react";
import Navbar from "../components/Navbar";
import { PortfolioMarketCard } from "../components/PortfolioMarketCard";
import styles from "../styles/Home.module.css";

const portfolio = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Polymarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="w-full flex flex-col sm:flex-row flex-wrap sm:flex-nowrap py-4 flex-grow max-w-5xl">
        <div className="w-full flex flex-col pt-1">
          <div className="p-10 bg-blue-700 rounded-lg flex flex-row justify-evenly">
            <div className="flex flex-col ">
              <h1 className="text-white opacity-50 text-base">
                Portfolio Value
              </h1>
              <h1 className="text-white text-2xl font-bold">$1,000,000</h1>
            </div>
            <div className="flex flex-col ">
              <h1 className="text-white opacity-50 text-base">
                Open Positions
              </h1>
              <h1 className="text-white text-2xl font-bold">$10,000</h1>
            </div>
          </div>
          <span className="font-bold my-3 text-lg">Your Market Positions</span>
          <PortfolioMarketCard />
          <PortfolioMarketCard />
        </div>
      </main>
    </div>
  );
};

export default portfolio;
