import Head from "next/head";
import Img from "next/image";
import React from "react";
import ChartContainer from "../../components/Chart/ChartContainer";
import { FavIcon } from "../../components/FavIcon";
import Navbar from "../../components/Navbar";

const details = () => {
  return (
    <div className="flex flex-col justify-center items-center h-full">
      <Head>
        <title>Polymarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="w-full flex flex-col sm:flex-row py-4 max-w-5xl">
        <div className="w-full flex flex-col pt-1">
          <div className="p-6 rounded-lg flex flex-row justify-start border border-gray-300">
            <div className="flex flex-row">
              <div className="h-w-15 pr-4">
                <Img
                  src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/isjFotcMs.PA/v1/1000x-1.jpg"
                  className="rounded-full"
                  width={55}
                  height={55}
                />
              </div>
              <div className="flex flex-col justify-start w-1/2 space-y-1">
                <span className="text-xs font-light text-gray-500">
                  US curreny affairs
                </span>
                <span className="text-lg font-semibold">
                  Will Terry McAuliffe win the general election for Governor of
                  Virginia in 2021?
                </span>
                <div className="flex-row flex items-center cursor-pointer">
                  <FavIcon size="3" />
                  <span className="text-xs text-gray-500 ml-1">Favorite</span>
                </div>
              </div>
            </div>
            <div className="flex flex-row items-center space-x-4">
              <div className="flex flex-col justify-start bg-gray-100 p-3">
                <span className="text-xs font-light text-gray-500 whitespace-nowrap">
                  Market End on
                </span>
                <span className="text-base font-semibold text-black whitespace-nowrap">
                  November 2, 2021
                </span>
              </div>
              <div className="flex flex-col justify-start bg-gray-100 p-3">
                <span className="text-xs font-light text-gray-500 whitespace-nowrap">
                  Total Volume
                </span>
                <span className="text-base font-semibold text-black whitespace-nowrap">
                  25,000
                </span>
              </div>
            </div>
          </div>
          <div className="flex flex-col space-y-3">
            <div className="w-full flex flex-row mt-5">
              <div className="w-2/3 border rounded-lg p-1 pb-4 border-gray-300 mr-2">
                <ChartContainer />
              </div>
              <div className="w-1/3 rounded-lg border border-gray-300 ml-2">
                <div className="flex flex-col items-start p-6">
                  <span className="text-lg font-bold m-auto pb-2">Buy</span>
                  <hr className="text-black w-full py-2" />
                  <span className="text-base">Pick Outcome</span>
                  <div className="w-full py-2 px-2 bg-green-500 text-white mt-2 cursor-pointer">
                    <span className="font-bold">YES</span> 78%
                  </div>
                  <div className="w-full py-2 px-2 bg-gray-100 mt-2 cursor-pointer">
                    <span className="font-bold">No</span> 22%
                  </div>
                  <span className="text-sm mt-5 mb-4">How much?</span>
                  <div className="w-full border border-gray-300 flex flex-row items-center">
                    <input
                      type="search"
                      name="q"
                      className="w-full py-2 px-2 text-base text-gray-700 border-gray-300 rounded-md focus:outline-none"
                      placeholder="0"
                      autoComplete="off"
                    />
                    <span className="whitespace-nowrap text-sm font-semibold">
                      POLY |{" "}
                    </span>
                    <span className="text-sm font-semibold text-blue-700 mx-2 underline cursor-pointer">
                      Max
                    </span>
                  </div>
                  <button className="mt-5 rounded-lg py-3 text-center w-full bg-blue-700 text-white">
                    Trade
                  </button>
                </div>
              </div>
            </div>
            <div className="w-2/3 flex flex-col">
              <span className="text-base font-semibold py-3">Description</span>
              <span>
                This market will resolve to “Yes” If H.R.3684 has “Become Law”
                (according to
                https://www.congress.gov/bill/117th-congress/house-bill/3684) by
                November 4, 2021, at 12:00 PM ET, and “No” otherwise. Credible
                news reports will be sufficient if the primary source is not
                updated by the resolution time.
              </span>
              <span className="text-base my-3 py-2 bg-gray-100 rounded-xl px-3">
                Resolution Source :{" "}
                <a className="text-blue-700" href="https://google.com">
                  https://google.com
                </a>
              </span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default details;
